adx_displayorder: 9
adx_enabletracking: false
adx_excludefromsearch: true
adx_hiddenfromsitemap: true
adx_name: Product B.png
adx_parentpageid: 87cdfb86-e3c8-48d7-8a99-c6fb2cbcb845
adx_partialurl: Product B.png
adx_publishingstateid: 38c7d71a-31fd-4c2a-b7b0-fa2cc7381654
adx_webfileid: f0cc058e-ff99-4ab5-b54d-dbeec5366fc1
annotationid: 59664d5b-aa9b-4626-8fef-e7506fe4c3cb
filename: Product B.png
isdocument: true
mimetype: image/png
objectid: f0cc058e-ff99-4ab5-b54d-dbeec5366fc1
objecttypecode: adx_webfile
