adx_displayorder: 9
adx_enabletracking: false
adx_excludefromsearch: true
adx_hiddenfromsitemap: true
adx_name: Product A.png
adx_parentpageid: 87cdfb86-e3c8-48d7-8a99-c6fb2cbcb845
adx_partialurl: Product A.png
adx_publishingstateid: 38c7d71a-31fd-4c2a-b7b0-fa2cc7381654
adx_webfileid: 70859fea-14df-4693-852d-8c159b08f742
annotationid: 08f80d69-fbb3-4a90-bb67-d1c36a4f27f9
filename: Product A.png
isdocument: true
mimetype: image/png
objectid: 70859fea-14df-4693-852d-8c159b08f742
objecttypecode: adx_webfile
