adx_displayorder: 1
adx_enablerating: false
adx_enabletracking: false
adx_excludefromsearch: false
adx_hiddenfromsitemap: false
adx_isroot: true
adx_name: Product A (sample)
adx_pagetemplateid: 60559fba-d1b3-4b64-ab9b-cbd6a1294ca1
adx_parentpageid: 4e5f61f6-a476-4e81-b69b-e4c3a30bc7ab
adx_partialurl: product-a
adx_publishingstateid: 38c7d71a-31fd-4c2a-b7b0-fa2cc7381654
adx_sharedpageconfiguration: false
adx_title: Product A (sample)
adx_webpageid: b79412fb-230b-4400-b773-ac2e54b9a451
