name: Update Pac

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Clone powerplatform-actions
        run: git clone https://github.com/microsoft/powerplatform-actions.git $RUNNER_TEMP/powerplatform-actions

      - name: Delete existing pac folder
        run: rm pac -rf
      
      - name: Copy pac folder from powerplatform-actions
        run: cp -r $RUNNER_TEMP/powerplatform-actions/dist/pac/tools pac
      
      - name: Configure git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Commit
        run: |
          git add .
          git commit -m "updated pac using workflow (run id $GITHUB_RUN_ID)" --author "${{ github.actor }}"
          git push