name: Update Pac

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Clone powerplatform-actions
        run: git clone https://github.com/microsoft/powerplatform-actions.git $RUNNER_TEMP/powerplatform-actions
